TABLE_DATA_TAGGER = [
    [
        "Tagger",
        "PosTagger",
        "flair",
        "tokens,labels",
    ],
    [
        "Tagger",
        "NerTagger",
        "flair",
        "tokens,labels",
    ],
    [
        "Tagger",
        "NerTagger",
        "cogie",
        "None",
    ],
    [
        "Tagger",
        "SpoTagger",
        "cogie",
        "None",
    ],
    [
        "Tagger",
        "SrlTagger",
        "allennlp",
        "tokens,arguments,roles",
    ],
    [
        "Tagger",
        "SrlTagger",
        "cogie",
        "None",
    ],
    [
        "Tagger",
        "EventTagger",
        "cogie",
        "None",
    ],
]


TABLE_DATA_LINKER=[
    [
        "Linker",
        "WikipediaLinker",
        "tagme",
        "begins,ends,ids,titles,mentions",
    ],
    [
        "Linker",
        "WikipediaLinker",
        "cogie",
        "None",
    ],
]

TABLE_DATA_SEARCHER=[
    [
        "Searcher",
        "WikipediaSearcher",
        "blink",
        "desc",
    ],
    [
        "Searcher",
        "WikipediaSearcher",
        "kilt",
        "None",
    ],
]

TABLE_DATA_EMBEDDER=[
    [
        "Embedder",
        "WikipediaEmbedder",
        "wikipedia2vec",
        "en_ebd,similar_ebd",
    ],
    [
        "Embedder",
        "WikipediaEmbedder",
        "cogkge",
        "None",
    ],
]